language: python
  python:
    - "3.6"
    - "3.7-dev"
    - "2.7"
  cache: pip
  install:
  - pip install pytest pytest-cov
  - pip install codecov
  script:
  - pytest --cov=./mgsub/
  after_success:
  - codecov
